### ISSUE TITLE
Compatible with Python 3.5.2?

### ISSUE THREAD

**Issue by dazzag24** [pycampers/zproc#2]
Looks like a really interesting project! 

The Pipfile states a requirement on 3.6, but I can't see this stated anywhere else?  Is this a hard requirement or would 3.5.2 also work?

Thanks

**Comment by devxpy** [comment]
Not its only compatible with 3.6

- used `pathlib
- think i also used `fstrings` but not sure.
- used the `secrets` module earlier, but then i ditched in favor of `uuid`

What OS are you on?
You can use [pyenv](https://github.com/pyenv/pyenv) for installing 3.6

**Comment by dazzag24** [comment]
Ubuntu 16.04.  I'll take a look at pyenv

**Comment by dazzag24** [comment]
Actually I installed on 3.5.2 and it seemed to work. Test pass and examples ran.

**Comment by devxpy** [comment]
Didn't know pathlib worked with 3.5, damn.

Will make sure to NOT use `fstrings` in future, I used a couple of them in my local branch. 

Thanks for the report!

**Comment by devxpy** [comment]
`setup.py` shall be fixed in next commit.

**Comment by devxpy** [comment]
I will also switch to 3.4 in my local development, since `pathlib` also works on 3.4.

Pipfile will be updated in the next release

**Comment by devxpy** [comment]
Looks like pathlib was incomplete in 3.4, 3.5 is the last supported version..

**Comment by devxpy** [comment]
It's done.

Let me know if you build something cool with it, new features, API restructuring.. anything ;)
